general:
  shutdown_graceperiod_seconds: 2
webserver:
  addr: <ADDR TO LISTEN ON>
  port: 8443
  ssl:
    key: server.key.pem
    cert: server.cert.pem
  cors:
    headers: ['X-Requested-With', 'Content-Type', 'Authorization']
    origins: ['*']
    methods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'OPTIONS']
application:
  item:
    name_min_length: 3
    name_max_length: 32
  credit:
    min: -9000
    max: 420230
auth:
  hash:
    rounds: 10
jwt:
  issuer: <TOKEN ISSUER, e.g. k4cg.org>
  sig:
    secret: <HASH SALT => random string, minimum length 32 characters>
  valid_sec: 
    default: <JWT TOKEN VALIDITY IN SECONDS>
    max: 15552000
db:
  sqlite3:
    items: ./db/matomat.db
    users: ./db/matomat.db
    items_stats: ./db/matomat.db
    user_items_stats: ./db/matomat.db
event_dispatching:
  mqtt:
    enabled: false
    client_id: matomat-server
    connection_string: <CONNECTION STRING, EXAMPLE: tcp://localhost:4242>
    topic: <NAME OF THE MQTT TOPIC, EXAMPLE: matomat>
    username: <USERNAME FOR MQTT BROKER>
    password: <PASSWORD FOR MQTT BROKER>
    retain_messages: true
